default_platform(:ios)

platform :ios do
  desc "打包iap"
  lane :TestBuild do  #函数名称，执行打包的时候使用

    gym(
#指定scheme的名字
scheme: "LeftSlideTest",
#输出的ipa名称
output_name:"LeftSlideTest",
# 是否清空以前的编译信息 true：是
clean:true,
# 指定打包方式，Release 或者 Debug
configuration:"Release",
# 指定打包所使用的输出方式，目前支持app-store, package, ad-hoc, enterprise, development
export_method:"ad-hoc",
# 指定输出文件夹，这里会保存我们最后生成的ipa文件，也就是存到了我们上面提到的fastlane文件夹中的build文件夹中
output_directory:"/Users/liujunwei/Desktop/builds/",
)

  end
end