
platform :ios do     #指定持续集成对象的平台名称
lane :dev do|options|      #给lane命名
branch = options[:branch]


#这里我们项目为了区分线上环境和测试环境，而做了两个target
#关于target区分环境的方法，可以参考我同事的简书文章https://www.jianshu.com/p/23cc84d40423
#下面代码通过在终端输入1或者其他数字来选择要打包的target
#puts是ruby中的输出，gets为获取终端中输入的文字，gets需要指定STDIN包中的gets方法，否则会识别为其他包中的gets方法，具体为什么我也不知道
scheme = "LeftSlideTest"
export_method = "ad-hoc"      
  
end

# 开始打包
gym(
#指定scheme的名字
scheme: "#{schemeName}",
#输出的ipa名称
output_name:"#{schemeName}",
# 是否清空以前的编译信息 true：是
clean:true,
# 指定打包方式，Release 或者 Debug
configuration:"Release",
# 指定打包所使用的输出方式，目前支持app-store, package, ad-hoc, enterprise, development
export_method:"#{export_method}",
# 指定输出文件夹，这里会保存我们最后生成的ipa文件，也就是存到了我们上面提到的fastlane文件夹中的build文件夹中
output_directory:"/Users/liujunwei/Desktop/builds/",
)

end
end