default_platform(:ios)

platform :ios do
  desc "打包iap"
  lane :TestBuild do  #函数名称，执行打包的时候使用

    time = Time.new.strftime("%Y%m%d") #获取时间格式
    version = get_version_number#获取版本号
    ipaName = "Release_#{version}_#{time}.ipa"
    gym(
       scheme:"LeftSlideTest", #项目名称
       export_method:"ad-hoc",#打包的类型
       configuration:"Release",#模式，默认Release，还有Debug
       output_name:"#{ipaName}",#输出的包名
       output_directory:"/Users/liujunwei/Desktop/builds"#输出的位置

     )

  end
end